### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by julia-light** [bnb-chain/greenfield-relayer#94]
#### System information

OS & Version: `Amazon Linux release 2023 (Amazon Linux)`
Commit hash : `8b6763fe78`  [tag: v0.2.6-hf.1]
GCC: gcc (GCC) `11.3.1 20221121`

#### Actual behaviour

`make build 
`

> go build -o build/greenfield-relayer -ldflags="-X github.com/bnb-chain/greenfield-relayer/version.AppVersion=v0.2.6-hf.1 -X github.com/bnb-chain/greenfield-relayer/version.GitCommit=8b6763fe7802c5ccd6ecd3dbb3c19c86fcd0bd31 -X github.com/bnb-chain/greenfield-relayer/version.GitCommitDate=20230924" main.go
>  command-line-arguments
> /usr/bin/ld: warning: static_code.o: missing .note.GNU-stack section implies executable stack
> /usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker

**Comment by alexgao001** [comment]
@julia-light it looks like a warning not error, could you paste if there is?

**Comment by julia-light** [comment]
> @julia-light it looks like a warning not error, could you paste if there is?

Hi, there are no other logs to paste here. The build result is a failure. Could I know how to resolve this?

**Comment by alexgao001** [comment]
@julia-light Can you help take a look under the build directory? The warning should not affect the binary building...

**Comment by anewt95** [comment]
#91
